"""empty message

Revision ID: 687a4fe02fa7
Revises: 6e9fd52f3cbc
Create Date: 2023-07-12 05:01:54.201385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "687a4fe02fa7"
down_revision = "6e9fd52f3cbc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("nickname", sa.String(), nullable=True),
        sa.Column("street1", sa.String(), nullable=True),
        sa.Column("street2", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("zipcode", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint("uq_address", "addresses", ["customer_id", "street1", "street2", "city", "state", "zipcode"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("addresses")
    # ### end Alembic commands ###
